// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCLIInstalledStatus() {
  return window['go']['main']['App']['GetCLIInstalledStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallCrunchyCLI() {
  return window['go']['main']['App']['InstallCrunchyCLI']();
}

export function LoginToCrunchyCLI() {
  return window['go']['main']['App']['LoginToCrunchyCLI']();
}
