// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function CreateUser(arg1:string):Promise<void>;

export function GetCLIInstalledStatus():Promise<boolean>;

export function GetUser(arg1:number):Promise<db.User>;

export function GetUsers():Promise<Array<db.User>>;

export function Greet(arg1:string):Promise<string>;

export function InstallCrunchyCLI():Promise<boolean>;

export function LoginToCrunchyCLI():Promise<boolean>;
