// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function CreateProfile(arg1:string):Promise<void>;

export function GetCLIInstalledStatus():Promise<boolean>;

export function GetConfig():Promise<db.Config>;

export function GetProfile(arg1:number):Promise<db.Profile>;

export function GetProfiles():Promise<Array<db.Profile>>;

export function Greet(arg1:string):Promise<string>;

export function InstallCrunchyCLI():Promise<boolean>;

export function LoginToCrunchyCLI():Promise<boolean>;

export function OpenVideoFolderDialog():Promise<string>;

export function SetConfigDirectory(arg1:string):Promise<void>;
