// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function GetCLIInstalledStatus() {
  return window['go']['main']['App']['GetCLIInstalledStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallCrunchyCLI() {
  return window['go']['main']['App']['InstallCrunchyCLI']();
}

export function LoginToCrunchyCLI() {
  return window['go']['main']['App']['LoginToCrunchyCLI']();
}

export function OpenVideoFolderDialog() {
  return window['go']['main']['App']['OpenVideoFolderDialog']();
}

export function SetConfigDirectory(arg1) {
  return window['go']['main']['App']['SetConfigDirectory'](arg1);
}
