// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCLIInstalledStatus():Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function InstallCrunchyCLI():Promise<boolean>;

export function LoginToCrunchyCLI():Promise<boolean>;
